SEMINARS = [
[1, 'Dr', 'Daniel', 'ROBYR', 'Department of Biological Chemistry, UCLA School of Medicine and Molecular Biology Institute, University of California Los Angeles, USA', 'Microarray deacetylation maps determine genome-wide functions for all yeast histone deacetylases', '2002-01-08 12:15:00', '410', 'ord', [15, nil]],
[2, 'Dr', 'Nicolas', 'FISCHER', 'NovImmune SA, Gen?ve', 'Generating novel folded protein domains by random polypeptide shuffling', '2002-01-15 12:15:00', '410', 'ord', [2, nil]],
[3, 'Prof', 'Claudio', 'DE VIRGILO', 'Département de Biochimie médicale, C M U - Centre Médical Universitaire, Genève', 'At the Rim(15) of the yeast Ras/cAMP pathway: identification of new downstream effectors involved in cell proliferation control', '2002-01-22 12:15:00', '410', 'ord', [3, nil]],
[4, 'Dr', 'Siva', 'REDDY', 'International Center for Genetic Engineering and Biotechnology, New Delhi, India ', 'Chloroplast genetic engineering for overproduction of foreign proteins: problems and perspectives ', '2002-01-30 12:15:00', '410', 'ord', [2, nil]],
[5, 'Dr', 'A.', 'MARTINEZ-ARIAS', 'Department of Genetics, University of Cambridge, Cambridge, U. K.', 'Cell signalling and cell polarity during morphogenesis in Drosophila', '2002-01-14 12:15:00', '410', 'ord', [8, 6]],
[6, 'Dr', 'Frank', 'LAFONT', 'Centre Médical Universitaire Département de Génétique et Microbiologie Genève', 'Molecular and cellular biology of host-pathogen interaction: rafts involvement during Shigella entry and development of new strategies to study infection in the central nervous system', '2002-03-26 12:15:00', '410', 'ord', [9, nil]],
[7, 'Dr', 'Susan', 'GERBI', 'Brown University Providence, USA', 'In the beginning....... Initiation of DNA replication', '2002-04-15 16:00:00', '410', 'ord', [10, nil]],
[8, 'Dr', 'Felix', 'KESSLER', 'ETH Zürich', 'A GTPase system in chloroplast protein import', '2002-04-30 13:00:00', '410', 'ord', [7, nil]],
[9, 'Prof', 'Davis B.', 'KNAFF', 'Texas Tech University, Lubbock, USA', 'Thioredoxin-regulation of chloroplast enzymes', '2002-05-13 16:00:00', '410', 'ord', [7, nil]],
[10, 'Dr', 'Izabela', 'SUMARA', 'IMP, Vienna, Austria', 'Regulation of vertebrate cohesin complexes by mitotic kinases in prophase', '2002-05-17 12:15:00', '410', 'ord', [15, nil]],
[11, 'Dr', 'Bruno', 'AMATI', 'Department of Oncology, DNAX Research Institute, Palo Alto, California, USA', 'Function of the c-Myc oncoprotein in chromatin remodeling and transcription', '2002-05-27 16:00:00', '410', 'ord', [15, nil]],
[12, 'Prof', 'M.', 'SPIESS', 'Biozentrum, Basel', 'Topogenesis of ER membrane proteins', '2002-05-28 12:15:00', '410', 'ord', [10, nil]],
[13, 'Dr', 'Andrea', 'MUSACCHIO', 'Department of Experimental Oncology, European Institute of Oncology, Milan, Italy', 'A ''safety belt'' binding mechanism at the heart of the spindle checkpoint: structure and function of the Mad1-Mad2 complex', '2002-06-13 12:15:00', 'A410', 'ord', [9, nil]],
[14, 'Dr', 'Ralph', 'STANEWSKY', 'Universität Regensburg, Institut für Zoologie, Lehrstuhl für Entwicklungsbiologie, Regensburg, Germany', 'Genetic analysis of the circadian system in Drosophila melanogaster', '2002-09-25 12:15:00', '410', 'ord', [5, nil]],
[15, 'Prof', 'Elaine', 'FUCHS', 'Rockefeller University, New York, NY, USA', 'Stem Cell Lineages of the Skin', '2002-10-01 16:00:00', 'A100', 'ord', [15, 13]],
[16, 'Prof', 'Ira', 'HERSKOWITZ', 'Department of Biochemistry & Biophysics University of California at San Francisco U S A ', 'The Sporulation Program of Budding Yeast', '2002-10-17 16:00:00', 'A150', 'ord', [5, nil]],
[21, 'Prof', 'John H.', 'MADDOCKS', 'Bernoulli Institute, EPFL (Swiss Federal Institute of Technology), Lausanne', 'Elastic rods and models of DNA deformability', '2002-12-11 12:15:00', '410', 'ord', [15, nil]],
[30, 'Prof', 'Titia', 'DE LANGE', 'The Rockefeller University, New York, NY ', 'Protection of Human Chromosome Ends ', '2003-01-22 12:15:00', 'A100', 'ord', [6, nil]],
[31, 'Prof', 'Wilhelm', 'GRUISSEM', 'Institute of Plant Sciences ETH Zentrum Zürich', 'Function of Retinoblastoma and MSl-related proteins in plant cell cycle control and differentiation', '2003-03-04 12:15:00', '410', 'ord', [2, nil]],
[32, 'Dr', 'Elisabeth', 'SALLER', 'MRC Laboratory of Molecular Biology, Cambridge, UK ', 'The transcriptional repressor Brinker antagonizes Wingless signaling ', '2003-03-05 16:00:00', '410', 'ord', [15, nil]],
[33, 'Dr', 'Linda', 'HENDERSHOT', 'St. Jude Children’s Research Hospital, Memphis, Tennessee, USA', 'BiP is a master regulator of endoplasmic reticulum function', '2003-04-14 12:15:00', '410', 'ord', [3, nil]],
[34, 'Dr', 'Giovanni', 'CENCI', 'Department of Genetics and Molecular Biology, University of Rome, “La Sapienza” ', 'Genetic and molecular analysis of Drosophila telomere capping', '2003-06-05 12:15:00', '410', 'ord', [6, nil]],
[35, 'Prof', 'Robert B.', 'DARNELL', 'Howard Hughes Medical institute, The Rockefeller University, New York, USA', 'Neuronal RNA binding proteins and brain disease: linking alternative splicing to the synapse', '2003-06-30 12:15:00', '410', 'ord', [9, nil]],
[36, 'Prof', 'Judith', 'JAEHNING', 'Department of Biochemistry and Molecular Genetics, University of Colorado, Health Sciences Center', 'Two Yeast RNA Polymerase Complexes: One Nuclear and the Other Mitochondrial', '2003-09-15 12:15:00', 'A50A', 'ord', [6, nil]],
[47, 'Dr', 'Martine', 'COLLART', 'C M U – Centre Médical Universitaire, Département de Biochimie médicale, Genève', 'Study of the conserved global transcriptional regulators NC2 and the Ccr4-Not complex, by genomic approaches in yeast', '2003-11-04 16:00:00', '3081', 'ord', [15, nil]],
[48, 'Prof', 'Nathan', 'NELSON', 'Department of Biochemistry, Faculty of Life Sciences, Tel Aviv University, Tel Aviv, Israël', 'The crystal structure of plant Photosystem I', '2003-12-10 12:15:00', '3081', 'ord', [2, nil]],
[49, 'Dr', 'Catherine', 'DARGEMONT', 'Institut Jacques Monod, Paris, France', 'Polyubiquitin and intracellular transport', '2004-01-16 12:15:00', '3081', 'ord', [17, nil]],
[50, 'Dr', 'Shulamit', 'MICHAELI', 'Bar-Ilan University, Israël ', 'Structure-function of the signal recognition particle: A lesson from trypanosomes ', '2004-02-02 12:15:00', '3079', 'ord', [10, nil]],
[52, 'Dr', 'Marco', 'FOIANI', 'FIRC Institute of Molecular Oncology, Milan, Italy ', 'Controlling genome integrity during chromosome replication ', '2004-03-23 16:00:00', '3079', 'ord', [6, nil]],
[53, 'Prof', 'François', 'GUILLEMOT', 'Division of Molecular Neurobiology, National Institute for Medical Research, The Ridgeway, Mill Hill, London ', 'Proneural genes and cell fate specification in the telencephalon ', '2004-03-29 13:00:00', 'A100', 'ord', [19, nil]],
[54, 'Dr', 'Edith', 'HEARD', 'Institut Curie, Epigenèse et développement des mammifères, UMR 218 – Dynamique nucléaire et plasticité du génome, Paris, France ', 'Epigenetics and nuclear compartmentalisation in X-chromosome inactivation ', '2004-04-01 16:00:00', '3079', 'ord', [15, nil]],
[55, 'Dr', 'Vincent', 'GELI', 'Laboratoire d’Ingénierie des Systèmes Macromoléculaires, CNRS, Marseille, France ', 'RPA dysfunction impairs EST1 binding and induces a DNA-damage response at telomeres', '2004-04-19 12:15:00', '3079', 'ord', [6, nil]],
[56, 'Dr', 'Katja', 'SEIPEL', 'Zoological Institute, University of Basel, Switzerland ', 'Molecular mechanisms of stem cell generation from adult tissues', '2004-04-21 15:00:00', '3079', 'ord', [9, nil]],
[57, 'Dr', 'José', 'SOGO', 'Institute of Cell Biology, ETH, Zurich ', 'Different roles of the rDNA enhancer in initiation of replication and mitotic recombination', '2004-05-04 12:15:00', '3079', 'ord', [6, nil]],
[58, 'Prof', 'Sidney', 'ALTMAN', 'Department of Molecular, Cellular and Developmental Biology,  Yale University, New Haven, USA', 'The role of RNase P in the control of gene expression ', '2004-04-26 16:15:00', '1S081', 'ord', [4, nil]],
[59, 'Dr', 'Elisa', 'IZAURRALDE', 'European Molecular Biology Laboratory, Heidelberg, Germany ', 'The interplay of post-transcriptional mechanisms that regulate gene expression ', '2004-05-14 12:15:00', '3079', 'ord', [4, nil]],
[60, 'Prof', 'Cris', 'KUHLEMEIER', 'University of Bern, Institute of Plant Sciences, Bern ', 'Plant stem cells and leaf development ', '2004-05-18 12:15:00', '3079', 'ord', [2, nil]],
[61, 'Dr', 'Gwendal', 'LAZENNEC', 'INSERM U450, Montpellier, France ', 'ERbeta and Interleukin-8, two factors involved in breast cancer development ', '2004-05-25 12:15:00', '3079', 'ord', [3, nil]],
[62, 'Prof', 'David M.', 'GILBERT', 'Department of Biochemistry and Molecular Biology, SUNY Upstate Medical University, Syracuse, N.Y., USA ', 'Spatial and temporal control of mammalian chromosome replication during the cell-cycle and development ', '2004-07-23 16:00:00', '3079', 'ord', [15, nil]],
[63, 'Dr', 'Bernhard', 'SUTER', 'Department of Molecular and Cell Biology, University of California, Berkeley, CA, USA ', 'The origin recognition complex links replication, sister chromatid cohesion, and transcriptional silencing ', '2004-07-27 12:15:00', '3079', 'ord', [15, nil]],
[64, 'Prof', 'Marc', 'GARTENBERG', 'UMDNJ-RWJMS, Department of Pharmacology, Piscataway, NJ, USA ', 'Pairing of sister chromatids by silent chromatin in budding yeast, and other amusing tales ', '2004-08-06 12:15:00', '3079', 'ord', [15, nil]],
[65, 'Dr', 'Felipe', 'SIERRA', 'Cell Structure and Function Program, Biology of Aging, National Institute of Aging - NIH, Bethesda, MD, USA ', 'Signal transduction and the proliferative response during aging –  A role for kininogens ', '2004-09-10 12:15:00', '3079', 'ord', [15, nil]],
[66, 'Dr', 'Colin', 'LOGIE', 'Nijmegen Center for Molecular, Life Sciences, Molecular Biology, Faculty of Natural Sciences, Nijmegen, The Netherlands', 'Cohesin, Condensin and RSC', '2004-09-01 16:00:00', '3079', 'ord', [15, nil]],
[67, 'Prof', 'Thomas D.', 'FOX', 'Department of Molecular Biology and Genetics, Biotechnology Building, Cornell University, Ithaca, NY, USA', 'Putting yeast mitochondrial gene products where they belong is not a simple matter: control and localization of translation within the organelle ', '2004-09-08 12:15:00', '3079', 'ord', [2, nil]],
[68, 'Dr', 'Dale', 'FRANK', 'Department of Biochemistry, Rappaport Medical School, Technion – Israel Institute of Technology, Haifa, Israel ', 'Meis3 Protein Regulates Brain Pattern Formation in Xenopus Embryo ', '2004-09-28 16:00:00', '3079', 'ord', [5, nil]],
[80, 'Dr', 'David', 'STERN', 'Boyce Thompson Institute, Department of Plant Biology, Cornell University, Ithaca, NY, USA ', 'Integration of chloroplast gene expression into the nutrient starvation response ', '2004-10-27 12:15:00', '3079', 'ord', [2, nil]],
[104, 'Dr', 'Javier', 'CACERES', 'MRC Human Genetics Unit, Edinburgh, UK ', 'Identification of RNA targets for SF2/ASF and hnRNP A1 ', '2006-10-11 12:15:00', '3079', 'ord', [9, nil]],
[105, 'Prof', 'Stan', 'FAKAN', 'Centre de Microscopie électronique, Université de Lausanne ', 'Ultrastructural analyses of functional nuclear architecture ', '2006-10-11 12:15:00', '3079', 'ord', [17, nil]],
[106, 'Prof', 'Iliana', 'FERRERO', 'Department of Genetics, Anthropology & Evolution, University of Parma, Italy ', 'Saccharomyces cerevisiae as a model organism for mitochondrial diseases ', '2006-12-07 10:00:00', '3079', 'ord', [6, nil]],
[107, 'Dr', 'Jürgen', 'BROSIUS', 'University of Münster, Germany ', 'The pervasive role of RNA in genome evolution and cellular function ', '2006-12-21 16:00:00', '3079', 'ord', [10, nil]],
[108, 'Prof', 'Benedikt', 'WESTERMANN', 'Zellbiologie, NWI, Universität Bayreut, Germany ', 'Molecular and cellular basis of mitochondrial dynamics ', '2007-01-17 12:15:00', '3079', 'ord', [21, nil]],
[109, 'Dr', 'Christophe', 'CARLES', 'Gene Expression and Epigenetics Unit, Laboratory of Integrative Biology and Molecular Genetics, CEA/Saclay, France', 'Is ribosome synthesis controlled by Pol I transcription ? ', '2007-02-21 14:00:00', '3079', 'ord', [6, nil]],
[110, 'Prof', 'Zoi', 'LYGEROU', 'Laboratory of General Biology, School of Medicine, University of Patras, Rio, Patras, Greece', 'Maintaining genome integrity: the licensing factor Cdt1 and its inhibitor Geminin in cell cycle control and tumorigenesis', '2007-02-27 16:00:00', '3079', 'ord', [24, nil]],
[111, 'Prof', 'Philippe', 'PASERO', 'IGH - Institute of Human Genetics, CNRS UPR 1142, Montpellier, France', 'Single-molecule analysis of replication fork arrest and recovery in yeast and human cells', '2007-04-12 16:00:00', '1S059', 'ord', [24, nil]],
[112, 'Dr', 'Marc', 'BUEHLER', 'Dept. of Cell Biology, Harvard Medical School, USA', 'Studies on the role of RNAi in initiation and maintenance of heterochromatin', '2007-04-23 12:15:00', '3079', 'ord', [6, nil]],
[113, 'Prof', 'Klas', 'WIMAN', 'Karolinska Institute, Department of Oncology-Pathology, Cancer Center Karolinska (CCK), Stockholm, Sweden', 'p53-induced apoptosis and cancer therapy', '2007-05-08 16:00:00', '3079', 'ord', [24, nil]],
[114, 'Dr', 'Knud', 'NIERHAUS', 'Max-Planck-Institut, Berlin', 'LepA, one of the most conserved proteins, is an elongation factor in all bacteria and mitochondria with a new function', '2007-05-07 16:00:00', '3079', 'ord', [10, nil]],
[115, 'Dr', 'Jesper Q.', 'SVEJSTRUP', 'Cancer Research UK, London Research Institute, Clare Hall Laboratories, Hertfordshire, United Kingdom', 'Transcription during DNA damage: collision and destruction', '2007-06-12 12:15:00', '3079', 'ord', [17, nil]],
[130, 'Dr', 'Curt', 'HARRIS', 'Laboratory of Human Carcinogenesis, National Cancer Institute, NIH, Bethesda, USA', 'Inflammation and Cancer: Interaction of Free Radical, microRNA and Cytokine Pathways ', '2007-10-02 16:00:00', '3079', 'ord', [24, nil]],
[151, 'Prof', 'Thanos', 'HALAZONETIS', 'University of Geneva', 'Welcome Note', '2008-02-26 15:30:00', 'A100', 'ord', [24, nil]],
[152, 'Dr', 'Peter', 'BAUMANN', 'Stowers Institute for Medical Research, Kansas City, USA ', 'Chromosome end protection - insights from yeast, lizards and humans', '2007-11-14 16:00:00', '3079', 'ord', [6, nil]],
[153, 'Dr', 'Reid', 'GILMORE', 'Biochemistry and Molecular Pharmacology, University of Massachusetts, Medical School, USA ', 'Interactions between the SRP receptor and the translocon beta-subunit simplify the search for a vacant protein translocation channel ', '2007-12-07 13:00:00', '3079', 'ord', [10, nil]],
[155, 'Dr', 'Aldo', 'PAGANO', 'Dipartimento di Oncologia Biologia e Genetica, Università degli Studi di Genova, Italy ', 'The contribution of the RNA Polymerase III to human diseases ', '2008-01-29 12:15:00', '3079', 'ord', [10, nil]],
[156, 'Prof', 'Winship', 'HERR', 'University of Lausanne', 'HCF-1: A two-for-one deal in human cell cycle regulation', '2008-02-26 15:35:00', 'A100', 'ord', [24, nil]],
[157, 'Prof', 'Giuseppe', 'PELLICCI', 'European Institute of Oncology', 'Title to be Announced', '2008-02-26 16:15:00', 'A100', 'ord', [24, nil]],
[158, 'Prof', 'Olli', 'KALLIONIEMI', 'VTT Technical Research Centre of Finland and University of Turku', 'Cell array technology for high-throughput screening', '2008-02-26 17:10:00', 'A100', 'ord', [24, nil]],
[159, 'Prof', 'Steve', 'JACKSON', 'University of Cambridge', 'The DNA-damage response: new molecular insights and new approaches to anti-cancer therapy', '2008-02-26 17:50:00', 'A100', 'ord', [24, nil]],
[160, 'Prof', 'Jiri', 'BARTEK', 'Danish Cancer Society', 'Final Note and End of Workshop', '2008-02-26 18:30:00', 'A100', 'ord', [24, nil]],
[161, 'Prof', 'Karl', 'GADEMANN', 'Chemical Synthesis Laboratory, EPFL, Lausanne', 'Natural Products as Tools in Chemical Biology: From Ecology To Functional Interfaces Directing Biological Response', '2008-03-04 09:45:00', '0009', 'ord', [29, nil]],
[162, 'Prof', 'Ed', 'HURT', 'Biochemie Zentrum, University of Heidelberg, Germany ', 'Formation of ribonucleoprotein particles and their export through nuclear pore complexes ', '2008-02-21 12:15:00', '3079', 'ord', [17, nil]],
[163, 'Prof', 'Shulamit', 'MICHAELI', 'Bar-IIan University, Israel ', 'The unique composition of the signal recognition particle in Trypanosomes and its role in protein translocation into the ER ', '2008-02-26 10:15:00', '3079', 'ord', [10, nil]],
[164, 'Dr', 'Dana', 'BRANZEI', 'F.I.R.C. Institute of Molecular Oncology, Milan, Italy ', 'Sumoylation regulated processes protecting the integrity of replicating chromosomes ', '2008-02-25 10:00:00', '3079', 'ord', [6, nil]],
[165, 'Dr', 'Remus', 'DAME', 'Department of Physics and Astronomy, Vrije Universiteit, Amsterdam, The Netherlands ', 'Unravelling bacterial chromatin organization: Insights from single-molecule experiments ', '2008-02-25 11:00:00', '3079', 'ord', [6, nil]],
[166, 'Dr', 'Stéphane', 'THORE', 'Institute of Molecular Biology and Biophysics, ETH-Zürich ', 'Structural study of the eukaryotic Thiamine pyrophosphate-binding riboswitch ', '2008-02-25 14:00:00', '3079', 'ord', [6, nil]],
[167, 'Dr', 'Georgios', 'SKINIOTIS', 'Harvard Medical School, Department of Cell Biology, Harvard Medical School, Boston, USA ', 'Visualization of dynamic protein systems by molecular electron microscopy ', '2008-02-25 15:00:00', '3079', 'ord', [6, nil]],
[168, 'Dr', 'Ivan', 'AHEL', 'Clare Hall Laboratories, South Mimms, U.K. ', 'Defective DNA damage response and human disease ', '2008-03-03 10:00:00', '3079', 'ord', [6, nil]],
[169, 'Dr', 'Thimo', 'KURZ', 'Institute of Biochemistry, ETH-Zürich ', 'Function and control of cullin-based E3 ubiquitin ligases ', '2008-03-03 11:00:00', '3079', 'ord', [6, nil]],
[170, 'Dr', 'Jung-Hyun', 'MIN', 'Memorial Sloan-Kettering Cancer Center, New York, USA ', 'Recognition of DNA damage by Xeroderma Pigmentosum C in Nucleotide Excision Repair ', '2008-03-03 14:00:00', '3079', 'ord', [6, nil]],
[171, 'Dr', 'Patrick', 'VIOLLIER', 'Department of Molecular Biology and Microbiology, Case Western Reserve University, School of Medicine, Cleveland, USA ', 'Function, cell cycle control and establishment of cell polarity in bacteria ', '2008-03-03 15:00:00', '3079', 'ord', [6, nil]],
[172, 'Dr', 'Wolfgang', 'ZACHARIAE', 'Max Planck Institute of Molecular Cell Biology and Genetics, Dresden, Germany ', 'Of daughters and sisters: control of chromosome segregation in meiosis ', '2008-03-04 11:00:00', '3079', 'ord', [6, nil]],
[182, '', 'Keji', 'ZHAO', 'Laboratory of Molecular Immunology (LMI), Division of Intramural Research (DIR), National Heart, Lung, and Blood Institute (NHLBI), National Institutes of Health (NIH), Bethesda ', 'Characterization of Human Epigenomes', '2008-06-12 12:15:00', '3079', 'ord', [5, nil]],
[186, '', 'Daniela', 'RHODES', 'Structural Studies unit of the MRC Laboratory of Molecular Biology, Cambridge, UK', 'Regulation of telomerase recruitment and telomere structure', '2008-07-07 11:00:00', '3079', 'ord', [6, nil]],
[202, '', 'Rolf', 'ZELLER', 'Developmental Genetics, Department of Biomedicine, University of Basel Medical Faculty', 'A Self-Regulatory System of Interlinked Signaling Feedback Loops Coordinately Controls Vertebrate Limb Growth and Patterning', '2008-10-28 16:00:00', 'A100', 'ord', [24, nil]],
[204, '', 'George', 'ILIAKIS', 'Institute of Medical Radiation Biology, University of Duisburg-Essen, Medical School, Essen, Germany', 'Repair of DNA Double Strand Breaks in cells of higher eukaryotes', '2009-02-23 16:00:00', 'A100', 'ord', [24, nil]],
[208, '', 'Peter K.', 'JACKSON', 'Genentech, South San Francisco, USA ', 'Assembly and Signaling of the Primary Cilium -or How to use Proteomics to Discover the Cell Biology Behind a Human Genetic Disease ', '2008-10-24 12:30:00', '3079', 'ord', [3, nil]],
[209, '', 'Rolf', 'ZELLER', 'Developmental Genetics, Department of Biomedicine, University of Basel Medical Faculty, Basel ', 'A Self-Regulatory System of Interlinked Signaling Feedback Loops Coordinately Controls Vertebrate Limb Growth and Patterning ', '2008-10-28 16:00:00', 'A100', 'ord', [24, nil]],
[212, '', 'Imre', 'BERGER', 'Structural Biology Group, EMBL Grenoble, France ', 'Towards Eukaryotic Structural Complexomics ', '2008-11-18 16:00:00', '3079', 'ord', [6, nil]],
[213, '', 'Pierre', 'THURIAUX', 'Service de Biochimie et de Génétique Moléculaire, CEA/Saclay, Gif-sur-Yvette, France ', 'When RNA polymerase react to nucleotide shortage : a case of gene-specific activation without activators ', '2008-12-01 12:15:00', '3079', 'ord', [6, nil]],
[228, '', 'Christian', 'FANKHAUSER', 'Center for Integrative Genomics, University of Lausanne ', 'A network of bHLH transcription factors controls plant growth in response to shade ', '2009-03-23 16:00:00', '3079', 'ord', [29, nil]],
[229, '', 'Alejandro', 'COLMAN-LERNER', 'Fisiologià y Biologià Molecular, Universidad de Buenos Aires, Argentina ', 'Dynamics of the activation of the mating pheromone response pathway in S.cerevisiae ', '2009-03-25 16:00:00', '3079', 'ord', [29, nil]],
[230, '', 'Christian', 'SPAHN', 'Institut für Medizinische Physik und Biophysik, CCM, Campus Charité Mitte, Berlin, Germany ', 'Structural analysis of translational GTPases bound to the ribosome by cryo- electron microscopy ', '2009-03-30 16:00:00', '3079', 'ord', [10, nil]],
[236, '', 'Sabeeha', 'MERCHANT', 'Department of Chemistry, UCLA, Los Angeles, USA ', 'RNA-seq analysis of the cooper-deficiency transcriptome of Chlamydomonas ', '2009-06-08 16:00:00', '3079', 'ord', [2, nil]],
[237, '', 'Dinshaw', 'PATEL', 'Structural Biology Program, Memorial Sloan-Kettering Cancer Center, New York, USA ', 'Small RNAs : mediators of gene regulation and silencing ', '2009-06-10 12:15:00', '3079', 'ord', [6, nil]],
[242, '', 'Brehon', 'LAURENT', 'Department of Pathology Cardiff University School of Medicine Cardiff, UK', 'RSC: to the ends', '2009-08-06 12:00:00', '3079', 'ord', [6, nil]],
[256, '', 'Vivek', 'RANGNEKAR', 'University of Kentucky, department of Microbiology, Immunology and Molecular Genetics, Lexington, USA', 'Par-4 intracellular and extracellular functions: a paradigm for cancer-selective apoptosis', '2009-09-07 16:00:00', '1S059', 'ord', [24, nil]],
[257, '', 'Mike', 'TYERS', 'Wellcome Trust Center for Cell Biology, University of Edinburgh, UK', 'Architecture of the yeast kinome', '2009-09-08 16:00:00', '3079', 'ord', [6, nil]],
[258, '', 'Charalambos', 'KYRIACOU', 'Department of Genetics, University of Leicester, UK', 'Evolutionary and ecological approaches to studying biological rhythms', '2009-09-09 12:15:00', '3079', 'ord', [5, nil]],
[17, 'Prof', 'Alain', 'Prochiantz', 'CNRS UMR 8542, Ecole Normale Superieure, Paris Cedex 5, 75230, France', 'Non-autonomous regulation of gene expression by messenger proteins', '2002-10-08 16:00:00', 'A100', 'lsss', [14, nil]],
[18, 'Prof', 'William', 'Martin', 'Institute of Botany III, Universität Düsseldorf, Universitätsstraße 1, D-40225 Düsseldorf, Germany', 'Hydrogenosomes: Unusual organelles of anaerobic ATP synthesis in amitochondriate protists and their possible evolutionary significance', '2002-11-05 16:00:00', 'A100', 'lsss', [14, nil]],
[19, 'Prof', 'Alex', 'VAN DER BLICK', 'Department of Biological Chemistry, University of California at Los Angeles, School of Medicine, Los Angeles, California 90095, USA. ', 'Mitochondrial division in C. elegans and in mammal', '2002-11-14 16:00:00', 'A100', 'lsss', [14, nil]],
[20, 'Prof', 'Ted', 'Farmer', 'Gene Expression Laboratory , Ecology Institute, University of Lausanne, 1015 Lausanne', 'Lipid regulators play key roles in the immune system of plants', '2003-01-17 16:00:00', 'A100', 'lsss', [14, nil]],
[22, 'Prof', 'Andrew', 'Clark', 'Department of Molecular Biology and Genetics, Cornell University, Ithaca, New York', 'Evolutionary inference from human-chimp-mouse gene alignments', '2003-02-03 16:00:00', 'A100', 'lsss', [5, nil]],
[23, 'Prof', 'Angus', 'Lamond', 'School of Life Sciences, The University of Dundee, Dow Street, Dundee, UK', 'Proteomic and dynamic studies on the cell nucleus', '2003-02-11 16:00:00', 'A100', 'lsss', [9, nil]],
[24, 'Prof', 'Olivier', 'Pourquie', 'Stowers Institute for Medical Research, Kansas City, USA', 'The vertebrate Segmentation clock', '2003-02-12 16:00:00', 'A100', 'lsss', [8, nil]],
[25, 'Prof', 'Martin', 'Raff', 'Medical Research Council Laboratory for Molecular Cell Biology, Cell Biology Unit, Department of Biology, University College, London, UK', 'Size control in animal development', '2003-03-11 16:00:00', 'A100', 'lsss', [14, nil]],
[26, 'Prof', 'Alan', 'Weiner', 'Department of Biochemistry, University of Washington, Seattle, USA', 'The CCA-adding enzyme: a remarkable RNA polymerase with a protein template', '2003-03-20 16:00:00', 'A100', 'lsss', [14, nil]],
[27, 'Prof', 'Tom', 'Rapoport', 'HHMI/Harvard Medical School, Department of Cell Biology, Boston, USA', 'Protein transport in and out of the ER', '2003-03-25 16:00:00', 'A100', 'lsss', [14, nil]],
[28, 'Prof', 'Meinrad', 'Busslinger', 'Research Institute of Molecular Pathology, Vienna Biocenter, Vienna, Austria', 'Transcriptional control of lineage commitment in the hematopoietic system', '2003-04-28 16:00:00', 'A100', 'lsss', [14, nil]],
[29, 'Prof', 'James', 'Spudich', 'Department of Biochemistry, Beckman Center, Stanfor University School of Medecine, Stanford, USA', 'Single Molecule Mechanics and the Myosin Family of Molecular Motors', '2003-05-13 16:00:00', 'A100', 'lsss', [14, nil]],
[37, 'Prof', 'Sandra', 'Baldauf', 'University of York, UK', 'The Deep Roots of Eukaryotes', '2003-11-18 16:00:00', 'A100', 'lsss', [16, 17]],
[38, 'Dr', 'John', 'Lucchesi', 'Emory University, USA', 'Dosage compensation in Drosophila: a model for the study of transcription regulation through chromatin remodeling', '2003-10-22 16:00:00', 'A100', 'lsss', [16, 17]],
[39, 'Dr', 'Andreas', 'Engel', 'University of Basel, Switzerland', 'Structure and dynamics of native membrane proteins assessed by high-resolution microscopy', '2003-12-05 16:00:00', 'A100', 'lsss', [16, 17]],
[40, 'Dr', 'Pascale', 'Cossart', 'Pasteur Institute, France', 'The entry of Listeria monocytogenes into cells: specificity, signaling and cytoskeleton rearrangements', '2004-01-13 16:00:00', 'A100', 'lsss', [16, 17]],
[41, 'Dr', 'Rob', 'Singer', 'Albert Einstein College of Medicine, USA', 'Following RNA Movement in Single Cells', '2004-02-10 16:00:00', 'A100', 'lsss', [17, nil]],
[42, 'Dr', 'Stephen', 'Cohen', 'European Molecular Biology Laboratory, Germany', 'MicroRNAs and the control of cell proliferation and apoptosis', '2004-03-01 16:00:00', 'A100', 'lsss', [5, nil]],
[43, 'Dr', 'Nori', 'Satoh', 'Kyoto University, Japan', 'Ciona intestinalis: A model for whole-genome analyses of development', '2004-04-07 16:00:00', 'A100', 'lsss', [8, nil]],
[44, 'Dr', 'Detlef', 'Weigel', 'Max Planck Institute Tubingen, Germany', 'Plant development: Insights from microarrays and microRNAs', '2004-04-27 16:00:00', 'A100', 'lsss', [7, nil]],
[45, 'Dr', 'Barbara', 'Meyer', 'University of California, Berkeley, USA', 'Chromosome-wide regulation in C. elegans: Targeting the Dosage Compensation Complex to X Chromosomes', '2004-05-24 16:00:00', 'A100', 'lsss', [6, nil]],
[46, 'Dr', 'Jim', 'Kadonaga', 'University of California, San Diego, USA', 'Fundamental aspects of transcription and chromatin dynamics', '2004-06-15 16:00:00', 'A100', 'lsss', [18, nil]],
[51, 'Dr', 'Jean-Pierre', 'CHANGEUX', 'Institut Pasteur, France', 'Le récepteur de l''acétylcholine: une protéine allostérique membranaire engagée dans la communication neuronale', '2004-02-02 17:30:00', 'A150', 'lsss', [16, nil]],
[69, 'Dr', 'Nicholas', 'Proudfoot', 'Sir William Dunn School of Pathology, University of Oxford, UK', 'Interconnections between mRNA 3'' end processing, transcription and chromatin structure', '2004-10-14 16:00:00', '1S081', 'lsss', [9, nil]],
[70, 'Dr', 'Pier Paolo', 'DI FIORE', 'FIRC Institute of Molecular Oncology, Italy', 'Ubiquitin and Ubiquitin receptors, a novel network of interactions in traffic and signalling', '2004-10-26 16:00:00', '1S081', 'lsss', [20, nil]],
[71, 'Dr', 'Caroline', 'Dean', 'Department of Molecular Genetics, John Innes Centre, UK', 'Vernalization - the need for winter in the switch to flowering', '2004-11-02 16:00:00', '1S081', 'lsss', [2, nil]],
[72, 'Dr', 'Phil', 'Ingham', 'Centre for Developmental Genetics, Department of Biomedical Science, University of Sheffield, UK', 'Genetic analysis of development in zebrafish', '2004-12-08 16:00:00', 'A100', 'lsss', [8, nil]],
[73, 'Dr', 'Peter', 'Sorger', 'MIT, USA', 'Chromosome segregation and genomic stability', '2005-01-18 16:00:00', '1S081', 'lsss', [6, nil]],
[74, 'Dr', 'Cliff', 'Tabin', 'Department of Genetics, Harvard Medical School, USA', 'Patterning the vertebrate limb and heart', '2005-02-04 16:00:00', '1S081', 'lsss', [8, nil]],
[75, 'Dr', 'Denise', 'Barlow', 'Center of Molecular Medicine, Austria', 'Genomic imprinting and non-coding RNAs', '2005-03-08 16:00:00', 'A100', 'lsss', [10, nil]],
[76, 'Dr', 'Pam', 'Silver', 'Silver Laboratory, Harvard Medical School, USA', 'Connecting the genome to the cytoplasm: from mechanism to medicine', '2005-03-15 16:00:00', 'A100', 'lsss', [17, nil]],
[77, 'Dr', 'Jürg', 'Tschopp', 'Institute of Biochemistry, University of Lausanne', 'Stressosomes: sensors of intracellular danger and activators of caspases', '2005-04-05 16:00:00', 'A100', 'lsss', [21, nil]],
[78, 'Dr', 'Graham', 'Warren', 'Department of Cell Biology, Yale University, USA', 'Biogenesis of the Golgi apparatus', '2005-05-10 16:00:00', 'A100', 'lsss', [22, nil]],
[79, 'Dr', 'Gary', 'Ruvkun', 'Department of Molecular Biology, Harvard Medical School, USA', 'Functional genomic analysis of microRNAs and RNAi in C. elegans', '2005-05-27 16:00:00', 'A100', 'lsss', [5, nil]],
[81, 'Prof', 'Danesh', 'Moazed', 'Harvard Medical School, USA ', 'Targeting RNAi to the Chromosome', '2005-09-29 16:00:00', 'A100', 'lsss', [6, nil]],
[82, 'Prof', 'Randy', 'Sheckman', 'UC Berkeley, USA', 'Transport vesicle biogenesis: mechanism and disease implications', '2005-10-12 16:00:00', 'A100', 'lsss', [20, nil]],
[83, 'Prof', 'Davor', 'Solter', 'MPI, Freiburg, Germany ', 'Epigenetic control of early mammalian development', '2005-12-07 16:00:00', 'A100', 'lsss', [8, nil]],
[84, 'Prof', 'Jim', 'Barber', 'Imperial College, London, UK', 'Structure of photosystem II and its implications for understanding the water splitting reaction', '2006-01-17 16:00:00', 'A100', 'lsss', [2, nil]],
[85, 'Prof', 'Adrian', 'Bird', 'University of Edinburgh, UK  ', 'Interpreting the DNA methylation signal ', '2006-02-01 16:00:00', 'A100', 'lsss', [5, nil]],
[86, 'Prof', 'Jean-Paul', 'Vincent', 'NIMR London, UK ', 'Trafficking of the Wingless signal in developing epithelia  ', '2006-02-07 16:00:00', '1S081', 'lsss', [3, nil]],
[87, 'Prof', 'David', 'Holden', 'Imperial College, London, UK', 'Intracellular activitiesof Salmonella', '2006-03-14 16:00:00', 'A100', 'lsss', [23, nil]],
[88, 'Prof', 'Hans-Ulrich', 'Hartl', 'MPIB Martinsried, Germany', 'Chaperone-assisted protein folding in the cytosol', '2006-04-25 16:00:00', 'A100', 'lsss', [3, nil]],
[89, 'Prof', 'Matthias', 'Hentze', 'EMBL Heidelberg, Germany', 'Mechanisms to control protein synthesis', '2006-05-08 16:00:00', 'A100', 'lsss', [9, nil]],
[90, 'Prof', 'Fotis', 'Kafatos', 'Imperial College, London, UK', 'Immunogenomic studies of malaria transmission in Anopheles', '2006-06-15 16:00:00', 'A150', 'lsss', [8, nil]],
[91, 'Prof', 'Uptal', 'Banerjee', 'UC Los Angeles, USA', 'Control of cell cycle and fate during Drosophila eye development', '2006-05-16 16:00:00', 'A100', 'lsss', [18, nil]],
[92, 'Prof', 'Suzanne', 'Pfeffer', 'Stanford University, USA', 'Regulation of receptor trafficking by Rab GTPases', '2006-10-17 16:00:00', '1S081', 'lsss', [23, nil]],
[93, 'Prof', 'Jiri', 'Bartek', 'Institute of Cancer Biology, Copenhagen, Denmark', 'DNA damage responses and human cancer', '2006-10-30 16:00:00', '1S081', 'lsss', [24, nil]],
[94, 'Prof', 'David', 'Holden', 'Imperial College, London, UK', 'Intracellular activities of Salmonella', '2006-11-07 16:00:00', 'A150', 'lsss', [23, nil]],
[95, 'Prof', 'Walter', 'Gehring', 'Biozentrum, Basel, Switzerland', 'Development and evolution of eyes and photoreceptors', '2006-11-28 16:00:00', '1S081', 'lsss', [18, nil]],
[96, 'Prof', 'Jane', 'Mellor', 'Oxford University, UK', 'Deciphering the histone code for transcription', '2007-01-09 16:00:00', '1S081', 'lsss', [6, nil]],
[97, 'Prof', 'Asifa', 'Akhtar', 'EMBL, Heidelberg, Germany', 'Dosage compensation: old complex new facts', '2007-01-23 16:00:00', '1S081', 'lsss', [5, nil]],
[98, 'Prof', 'Jacques', 'Pouyssegur', 'Centre A. Lacassagne CNRS Nice, France', 'Hypoxia signalling, metabolism and tumor regression', '2007-02-07 16:00:00', 'A100', 'lsss', [21, nil]],
[99, 'Prof', 'Giulio', 'Superti-Furga', 'Austrian Academy of Sciences, Vienna, Austria', 'Proten networks and drug action', '2007-03-06 16:00:00', '1S081', 'lsss', [10, nil]],
[100, 'Prof', 'Michael', 'Kastan', 'St. Jude Children’s Research Hospital, Memphis, USA', 'Molecular controls of the ATM-p53 pathway', '2007-03-27 16:00:00', 'A100', 'lsss', [24, nil]],
[101, 'Prof', 'Art', 'Johnson', 'Texas A&M University, USA', 'Fluorescence-detected protein trafficking into and out of the ER', '2007-04-03 16:00:00', 'A100', 'lsss', [10, nil]],
[102, 'Prof', 'Nenad', 'Ban', 'ETH Zurich, Swizerland', 'Structure and function of large macromolecular assemblies involved in central cellular processes', '2007-04-17 16:00:00', '1S081', 'lsss', [20, nil]],
[103, 'Prof', 'W. James', 'NELSON', 'Stanford University, USA', 'Biogenesis of epithelial cell polarity', '2007-06-22 16:00:00', 'A100', 'lsss', [16, nil]],
[116, 'Prof', 'Raphael', 'KOPAN', 'Department of Molecular Biology and Pharmacology and the Department of Medicine (Division of Dermatology), Washington University, USA', 'Theme and variation in Notch signaling', '2007-09-14 16:00:00', 'A100', 'lsss', [8, nil]],
[117, 'Dr', 'Venki', 'RAMAKRISHNAN', 'Structural Studies Division, MRC Laboratory of Molecular Biology, Cambridge, UK', 'Insights into translation from structures of the ribosome', '2007-09-28 16:00:00', 'A100', 'lsss', [6, nil]],
[118, 'Dr', 'Armand-Marie', 'LEROI', 'Department of Biological Sciences, Silwood Park Campus, Imperial College London, UK', 'Regulation of Growth in Caenorhabditis elegans', '2007-10-16 16:00:00', 'A100', 'lsss', [25, nil]],
[119, 'Prof', 'David', 'RUSSELL', 'Microbiology and Immunology, College of Veterinary Medicine, Cornell University, USA', 'Mycobacterium tuberculosis and the environment within the phagosome', '2007-11-20 16:00:00', 'A100', 'lsss', [23, nil]],
[120, 'Prof', 'Witold', 'FILIPOWICZ', 'Friedrich Miescher Institute, Basel', 'Mechanisms and reversibilty of miRNA-mediated repression', '2007-12-04 16:00:00', 'A100', 'lsss', [17, nil]],
[121, 'Prof', 'Claude', 'DESPLAN', 'Center for Developmental Genetics, Dept. Biology, NY, USA', 'Detection and Processing of color information (in Drosophila)', '2007-12-18 16:00:00', 'A100', 'lsss', [3, nil]],
[122, 'Prof', 'Klaus', 'APEL', 'Institut für Pflanzenwissenschaften, ETH, Zurich', 'The genetic basis of singlet oxygen-mediated stressresponses in higher plants', '2008-01-22 16:00:00', 'A100', 'lsss', [2, nil]],
[123, 'Prof', 'Peter', 'FRASER', 'The Babraham Institute, Babraham Research Campus, Cambridge, UK', 'Transcription factories and nuclear organization of the genome', '2008-02-05 16:00:00', 'A100', 'lsss', [6, nil]],
[124, 'Prof', 'George', 'COUPLAND', 'Max-Planck-Institute for Plant Breeding Research, Department of Plant Developmental Biology, GERMANY', 'The control of flowering by seasonal cues', '2008-03-04 16:00:00', 'A100', 'lsss', [28, nil]],
[125, 'Prof', 'Paul', 'SCHULZE-LEFERT', 'Max Planck Institute for Plant Breeding Research, GERMANY', 'Signal integration in the plant immune system', '2008-04-29 16:00:00', 'A100', 'lsss', [28, nil]],
[126, 'Prof', 'Robb', 'KRUMLAUF', 'Stowers Institute, USA', 'Hox genes and regulation of head development', '2008-05-27 16:00:00', 'A100', 'lsss', [8, nil]],
[129, 'Prof', 'François', 'SCHWEISGUTH', 'Ecole Normale Supérieure, Paris, France', 'Role of endocytosis in Delta signaling in Drosophila', '2008-04-01 16:00:00', 'A100', 'lsss', [26, nil]],
[187, '', 'Vivek', 'MALHOTRA', 'Centre for Genomic Regulation, Barcelona, Spain', 'Protein secretion in health and disease', '2008-09-30 16:00:00', 'A100', 'lsss', [26, nil]],
[188, '', 'Ingrid', 'GRUMMT', 'German Cancer Research Center, Heidelberg, Germany', 'Non-coding RNA  and chromatin remodeling in ribosomal gene transcription', '2008-10-14 16:00:00', 'A100', 'lsss', [5, nil]],
[189, '', 'Vicki', 'CHANDLER', 'University of Arizona, Tucson, USA', 'Interchromosomal Mediated Epigenetic Silencing Across Generations', '2008-11-04 16:00:00', 'A100', 'lsss', [28, nil]],
[190, '', 'Tony', 'HYMAN', 'Max Planck Institut, Dresden, Germany', 'Centrosomes: organizers of cell division in C. elegans', '2008-12-02 16:00:00', 'A100', 'lsss', [16, nil]],
[191, '', 'Regine', 'KAHMANN', 'Max Planck Institut, Marburg, Germany', 'Novel effectors affecting the interaction of a fungus with its host plant', '2008-12-16 16:00:00', 'A100', 'lsss', [2, nil]],
[192, '', 'Katia', 'GEORGOPOULOS', 'Harvard University, Cambridge, USA', 'Chromatin regulation of cell fate decisions in  early hematopoiesis', '2009-01-06 16:00:00', 'A100', 'lsss', [24, nil]],
[193, '', 'Bruno', 'LEMAITRE', 'Global Health Institute, EPFL, Lausanne, Switzerland', 'The gut immune response of Drosophila', '2009-01-20 16:00:00', 'A100', 'lsss', [26, nil]],
[194, '', 'Gero', 'MIESENBOECK', 'Oxford University, Oxford, UK', 'Change of Mind: Optical Control of Neural Circuits and Behavior', '2009-02-03 16:00:00', 'A100', 'lsss', [18, nil]],
[195, '', 'Ottoline', 'LEYSER', 'University of York, York, UK', 'Signal integration in the control of shoot branching', '2009-03-09 16:00:00', 'A100', 'lsss', [28, nil]],
[196, '', 'Lalita', ' RAMAKRISHNAN', 'University of Washington, Seattle, USA', 'Monitoring and modulating tuberculosis in the transparent zebrafish', '2009-04-21 16:00:00', 'A100', 'lsss', [23, nil]],
[197, '', 'Fiona', 'WATT', 'Cancer Research UK, Cambridge, UK', 'Stem Cells in Mammalian Epidermis', '2009-05-12 16:00:00', 'A100', 'lsss', [22, nil]],
[198, '', 'Anne', 'EPHRUSSI', 'EMBL Heidelberg, Germany', 'oskar RNP assembly for coordinated RNA transport and translation control', '2009-06-02 16:00:00', 'A100', 'lsss', [17, nil]],
[199, '', 'Johan', 'AUWERX', 'EPFL, Lausanne, Switzerland', 'A cofactor network that controls metabolism', '2009-06-16 16:00:00', 'A100', 'lsss', [3, nil]],
[200, '', 'Detlev', 'ARENDT', 'EMBL Heidelberg, Germany', 'The evolution of the central nervous system in animals', '2009-03-24 16:00:00', 'A100', 'lsss', [30, nil]],
[243, '', 'Alan', 'HINNEBUSCH', 'Laboratory of Gene Regulation and Development, Eunice Kennedy Shriver National Institute of Child Health and Human Development, Bethesda, USA', 'Regulation of Start site selection by scanning ribosomes', '2009-09-15 16:00:00', 'A100', 'lsss', [29, nil]],
[244, '', 'Juan', 'BONIFACINO', 'Cell Biology and Metabolism Program, Eunice Kennedy Shriver National Institute of Child Health and Human Development, NIH, Bethesda, USA', 'Sorting of the amyloid precursor protein mediated by the AP-4 adaptor', '2009-09-29 16:00:00', 'A100', 'lsss', [22, nil]],
[245, '', 'Wolfhard', 'ALMERS', 'Vollum Institute, Oregon Health & Science University, Portland, USA', 'The microphysiology of exocytosis', '2009-10-26 16:00:00', 'A100', 'lsss', [23, nil]],
[246, '', 'Gero', 'MIESENBOECK', 'Department of Physiology, Anatomy and Genetics, Oxford University, UK', 'Change of mind: optical control of neural circuits and behavior', '2009-11-10 16:00:00', 'A100', 'lsss', [18, nil]],
[247, '', 'Bertrand', 'SERAPHIN', 'CNRS, Centre de Génétique Moléculaire, Gif-Sur-Yvette, FRANCE', 'CUTting RNAs', '2009-11-24 16:00:00', 'A100', 'lsss', [31, nil]],
[248, '', 'Matthias', 'PETER', 'Institut für Biochemie, ETH, Zürich', 'Function and regulation of cullin-based ubiquitin ligases', '2009-12-15 16:00:00', 'A100', 'lsss', [3, nil]],
[249, '', 'Ueli', 'GROSSNIKLAUS', 'Institute of Plant Biology, University of Zurich', 'Sex, parental conflict and infanticide: the regulation of genomic imprinting in Arabidopsis', '2010-01-12 16:00:00', 'A100', 'lsss', [32, nil]],
[250, '', 'Regine', 'KAHMANN', 'Max Planck Institute for Terrestrial Microbiology, Marburg, Germany', 'Novel effectors affecting the interaction of a fungus with its host plant', '2010-02-23 16:00:00', 'A100', 'lsss', [2, nil]],
[251, '', 'Nils', 'LARSSON', 'Max Plank Institute for Biology and Ageing, Cologne, Germany', 'Mitochondrial dysfunction in degenerative diseases and ageing', '2010-03-23 16:00:00', 'A100', 'lsss', [21, nil]],
[252, '', 'Andrew', 'FIRE', 'Stanford University School of Medicine, USA', 'Living with diversity in innate and acquired immune repertoires', '2010-05-04 16:00:00', 'A100', 'lsss', [33, nil]],
[253, '', 'Joan', 'STEITZ', 'HHMI, Yale School of Medicine, USA', 'Regulating the activity of microRNAs', '2010-05-14 16:00:00', 'A100', 'lsss', [33, nil]],
[254, '', 'Scott', 'EMR', 'Cornell University, USA', 'Receptor endocytosis and down-regulation: role for the ESCRT and ART protein complexes', '2010-05-18 16:00:00', 'A100', 'lsss', [20, nil]],
[255, '', 'Elisabetta', 'DEJANA', 'IFOM-FIRC, University of Milan, Italy', 'The role of canonic Wnt signalling in the development of the vascular system', '2010-06-15 16:00:00', 'A100', 'lsss', [16, nil]]
]

# INSERT INTO `adm_host` (`hostID`, `title`, `f_name`, `l_name`, `interne`, `email`) VALUES
HOSTS = [
[3, 'Prof.', 'Didier', 'Picard', '96813', 'Didier.Picard@unige.ch'],
[4, 'Prof.', 'Ulrich', 'Laemmli', '96122', 'Ulrich.Laemmli@unige.ch'],
[2, 'Prof.', 'Jean-David', 'Rochaix', '96187', 'Jean-David.Rochaix@unige.ch'],
[5, 'Prof.', 'Ueli', 'Schibler', '96175', 'ueli.schibler@unige.ch'],
[6, 'Prof.', 'David', 'Shore', '96183', 'david.shore@unige.ch'],
[8, 'Prof.', 'Denis', 'Duboule', '96771', 'Denis.Duboule@unige.ch'],
[9, 'Prof.', 'Angela', 'Krämer', '96750', 'Angela.Kraemer@unige.ch'],
[10, 'Dr.', 'Katharina', 'Strub', '96724', 'Katharina.Strub@unige.ch'],
[13, 'Dr.', 'Christoph', 'Bauer', '96743', 'Christoph.Bauer@unige.ch'],
[14, 'Dr.', 'Steve', 'Brown', '96176', 'steven.brown@unige.ch'],
[16, 'Dr.', 'Sandra', 'Citi', '96182', 'sandra.citi@unige.ch'],
[17, 'Dr.', 'Françoise', 'Stutz', '96729', 'francoise.stutz@unige.ch'],
[18, 'Dr.', 'François', 'Karch', '96331', 'Francois.Karch@unige.ch'],
[19, 'Dr.', 'Jean-Marc', 'Matter', '96492', 'Jean-Marc.Matter@unige.ch'],
[20, 'Prof.', 'Howard', 'Riezman', '96469', 'Howard.Riezman@unige.ch'],
[21, 'Prof.', 'Jean-Claude', 'Martinou', '96443', 'Jean-Claude.Martinou@unige.ch'],
[22, 'Prof.', 'Jean', 'Gruenberg', '96487', 'Jean.Gruenberg@unige.ch'],
[23, 'Dr.', 'Thierry', 'Soldati', '96496', 'Thierry.Soldati@unige.ch'],
[24, 'Prof.', 'Thanos', 'Halazonetis', '96112', 'Thanos.Halazonetis@unige.ch'],
[25, 'Dr.', 'Roland', 'Dosch', '93280', 'Roland.Dosch@unige.ch'],
[26, 'Prof.', 'Marcos', 'González-Gaitán', '96461', 'Marcos.Gonzalez@unige.ch'],
[27, 'Dr.', 'Silvia', 'Martin Lluesma', '96749', 'Silvia.MartinLluesma@unige.ch'],
[28, 'Prof.', 'Jerzy', 'Paszkowski', '93021', 'Jerzy.Paszkowski@unige.ch'],
[29, 'Prof.', 'Robbie', 'Loewith', '96116', 'Robbie.Loewith@unige.ch'],
[30, 'Dr.', 'Brigitte', 'Galliot', '96667', 'Brigitte.Galliot@unige.ch'],
[31, 'Dr.', 'Stéphane', 'Thore', '96127', 'Stephane.Thore@unige.ch'],
[32, 'Prof.', 'Michel', 'Goldschmidt-Clermont', '96188', 'Michel.Goldschmidt-Clermont@unige.ch'],
[33, '', 'Silvia', 'Ramundo', '96190', 'Silvia.Ramundo@unige.ch']
]


namespace :roggli do
  desc "Enter roggli's seminars"
  task :seminars => :environment do
    new_seminars = []
    for s in SEMINARS
      sem = Seminar.new
      sem.start_on = s[6]
      sem.end_on = sem.start_on+1.hour unless sem.start_on.nil?
      sem.location = Location.find_or_initialize_by_name(s[7])
      sem.location.building = Building.find_by_name('Sciences III') if !sem.location.name.blank? and sem.location.building.blank?
      sem.category = s[8] == 'lsss' ? Category.find_by_name('Life Science Seminar Series') : Category.find_by_name('Dpt of Molecular Biology')
      for h in s[-1]
        unless h.nil?
          h_from_hosts = HOSTS.detect{|i| i[0] == h}
          unless h_from_hosts.nil?
            host = Host.find_by_email(h_from_hosts[-1].downcase)
            host = Host.find_by_name(h_from_hosts[2].capitalize+' '+h_from_hosts[3].capitalize) if host.nil?
            if host.nil?
              sem.hosts.build(:email => h_from_hosts[-1].downcase, :name => h_from_hosts[2].capitalize+' '+h_from_hosts[3].capitalize)
            else
              sem.hosts << host
            end
          end
        end
      end
      sem.speakers.build(:name => s[2]+' '+s[3].capitalize, :affiliation => s[4], :title => s[5])
      sem.user = User.find_by_email('nicolas.roggli@unige.ch'.downcase)
      
      if sem.hosts.blank?
        puts "seminar #{sem.mini_seminar_title} not saved: hosts is blank"
      elsif sem.speakers.blank?
        puts "seminar #{sem.mini_seminar_title} not saved: speakers is blank"
      elsif !Seminar.all.select{|t| t.mini_seminar_title == sem.mini_seminar_title}.blank?
        puts "seminar #{sem.mini_seminar_title} not saved: title already exists"
      elsif !sem.save
        puts "seminar #{sem.mini_seminar_title} not saved!!! (#{sem.errors.full_messages.to_sentence} - #{sem.hosts.first.errors.full_messages.to_sentence})"
      end
    end
  end
end