source 'http://rubygems.org'

gem 'rails', '3.0.10'
gem 'rake', '0.8.7'

gem 'mysql2', '0.2.13'
gem "haml-rails"
gem 'sass'
gem "devise"
gem "cancan"
gem "hpricot"
gem "ruby_parser"
gem "jquery-rails"
gem 'icalendar'
gem 'paperclip'
gem "bio", '1.4.0'
gem "calendar_date_select"
gem 'htmlentities'
gem 'will_paginate', '~>3.0.2'
gem 'rails3-generators'
gem 'airbrake'
gem "newrelic_rpm"

group :test, :development do  
  gem "shoulda", ">=2.11.2"
  gem "factory_girl", ">=1.3.2"
  gem "factory_girl_rails"
  gem 'capybara'
  gem "capybara-envjs"
  gem 'database_cleaner'
  # gem 'timecop'
end 