development:
  adapter: mysql2
  encoding: utf8
  database: seminars_development
  username: yannis
  password: '2375'
  
test:
  adapter: mysql2
  encoding: utf8
  database: seminars_test
  username: yannis
  password: '2375'
  
production:
  adapter: mysql2
  encoding: utf8
  database: seminars_production
  username: seminarsmaster
  password: sdb@stag$
  host: localhost
