development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: seminars_development
  pool: 5
  username: yannis
  password: 2375
  socket: /tmp/mysql.sock
  
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: seminars_test
  pool: 5
  username: yannis
  password: 2375
  socket: /tmp/mysql.sock
  
production:
  adapter: mysql
  encoding: utf8
  database: seminars_production
  username: seminarsmaster
  password: sdb@stag$
  host: 127.0.0.1
